apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-aerospike-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-aerospike-app
  template:
    metadata:
      labels:
        app: test-aerospike-app
    spec:
      containers:
        - name: test-aerospike-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: AEROSPIKE_HOST
              value: "{{ .Values.aerospike.host }}"
