apiVersion: v1
kind: Service
metadata:
  name: test-aerospike-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: test-aerospike-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
